### ISSUE TITLE
UPS not working

### ISSUE THREAD

**Issue by sleepydiode** [egg-/delivery-tracker#14]
Looks like the response here says: 

The response body for the UPS request is: `body: '{"unauthorized":401}'`

**Comment by egg-** [comment]
hi, please let me know the tracking number for testing.

**Comment by Beedug** [comment]
Hello I am not the orignal post but this is a UPS tracking number that does not work 1Z62WF001333806039

**Comment by sleepydiode** [comment]
Here are some more example tracking numbers: 

1ZW9852A0300287423
1z7ae1090309775218
1z4731610368485284
1z2599700396627831
