### ISSUE TITLE
Questions on API limitations 

### ISSUE THREAD

**Issue by alex-sf** [egg-/delivery-tracker#17]
This is just a functionality question but we're looking for a general purpose api for tracking shipments to integrate into our application. This packages is exactly what we were looking for. But have you found any limitations to the APIs you are hitting? ie Daily/Hourly frequency caps

**Comment by egg-** [comment]
Dear @alex-sf 

Sorry for the late reply.
There are no restrictions on the package itself.

However, restrictions may exist for each shipping company.
Most of the logic is crawling and using the carrier's web pages, so if there are a lot of requests, your server may be blocked.

Thank you.
