### ISSUE TITLE
UPS invalid dates

### ISSUE THREAD

**Issue by ghost** [egg-/delivery-tracker#2]
All of the `result.checkpoints.time` fields returned by UPS are set to `'Invalid Date'`.

**Comment by egg-** [comment]
I am sorry to be late and I will check the issue and fix it as soon as possible.
Is tracking code sharing possible to verify reproduction?

**Comment by ghost** [comment]
> Is tracking code sharing possible to verify reproduction?

I can't, unfortunately.
