### ISSUE TITLE
Canada Post Tracking

### ISSUE THREAD

**Issue by steveny9911** [egg-/delivery-tracker#23]
Just wondering if there's plan for adding Canada Post tracking.
They have "unofficial" JSON APIs for tracking multiple packages summary and single package details:

```
GET https://www.canadapost-postescanada.ca/track-reperage/rs/track/json/package?pins=
```
```
GET https://www.canadapost-postescanada.ca/track-reperage/rs/track/json/package/
```

Would love to take a look and help out or make a full request.

**Comment by egg-** [comment]
Added tracker. (1ce4015ffaec9cc06c2a2c62e24e40189c3d19e7)
