### ISSUE TITLE
The delivery-tracker is not work with UPS.

### ISSUE THREAD

**Issue by phamvannam** [egg-/delivery-tracker#24]
Dear,
From 1 day ago. I see, our's library is not working for requests to UPS service to get tracking.
I was tested with the same tracking number on the UPS website that is response result ok. But that does not work with our system.
What happened with our's system? Did the UPS have any update and we out an update?
My test: with new version 2.7.0
delivery-tracker -c UPS 1Z4566F5NT41188xxx
Many Thanks

**Comment by egg-** [comment]
@phamvannam 

Can I get the tracking number to test?

Thank you.

**Comment by yaliya** [comment]
Hello,

I ran into the same problem. I cannot test the service since i do not have tracking numbers.
Can you provide some or at least tell me where did you find some during testing ?

Thanks

**Comment by yaliya** [comment]
I would also like to know where can you find some tracking numbers for Canada Post

**Comment by phamvannam** [comment]
> @phamvannam
> 
> Can I get the tracking number to test?
> 
> Thank you.

Hi @egg- Thanks for rep. I have found the issue is coming from UPS. and they was fixed that, Many Thanks

**Comment by egg-** [comment]
@phamvannam 
okay. noted.
thank you~ !!
