### ISSUE TITLE
Acquiring Test Tracking Numbers

### ISSUE THREAD

**Issue by JeffResc** [egg-/delivery-tracker#27]
Hello,

Thanks for the great project, it’s really helping with a project that I’m working on. I’m interested in adding another courier to this, which I’m fully capable of doing myself, but I’m wondering how you go about getting test Tracking IDs to test with. I have a few parcels with this courier, but I doubt they could reach all needed test cases. Would I have any luck contacting the courier directly for this?

Courier: https://asendiausa.com

**Comment by egg-** [comment]
Hi,

I think it's a good way to contact them for a test case.
But I don't think they're going to share it because it's the customer's personal data.

Even if it is incomplete, it is recommended to make a test dummy with the information you have.

Thank you.
