### ISSUE TITLE
USPS no longer working

### ISSUE THREAD

**Issue by pbmzero** [egg-/delivery-tracker#33]
I'm using version 2.7.2 with USPS tracking numbers, even if valid on the USPS website seem to only return the response 
`{ code: 10, message: 'invalid trace number.' }`

The issue started seemingly 2022-09-19 and continues to this morning.   Perhaps there is a change or restriction upstream?

**Comment by pbmzero** [comment]
Digging further i do see this pull request https://github.com/qcasey/delivery-tracker/tree/fix/usps-design-09-2022
I took some time to check out the PR and verify that it solves the issue.

**Comment by egg-** [comment]
sorry for the late reply.
I have merged it successfully.
thank you.
