### ISSUE TITLE
USPS Tracking Does Not Work

### ISSUE THREAD

**Issue by ss5nathan** [egg-/delivery-tracker#37]
First off, thank you for creating this repo, it has been awesome! Recently USPS has not been working, here is an example tracking number:

https://tools.usps.com/go/TrackConfirmAction.action?tLabels=9400111206217036095304
9400111206217036095304

**Comment by ss5nathan** [comment]
@egg- do you still occasionally maintain this?

**Comment by egg-** [comment]
hello ss5nathan,

It has been fixed, but the USPS site often does not work.

**Comment by ss5nathan** [comment]
Looks great on my end, thank you for adding the fix!

**Comment by ELY3M** [comment]
it is not working now.   

delivery-tracker -c USPS 9361289722660264016923
{
  "courier": {
    "code": "usps",
    "name": "USPS"
  },
  "number": "",
  "status": "Pending",
  "checkpoints": []
}

it should show delivered
