### ISSUE TITLE
Bad error handling and crash

### ISSUE THREAD

**Issue by gevorggalstyan** [egg-/delivery-tracker#4]
In fedex.js line 101 looks like this
```js
var results = parser.trace(body.TrackPackagesResponse.packageList);
```
 and you do not handle the res correctly. request does not return error if the request response was actually an http error. and because of that you are not handling all error from the provider. 

For example, fedex sometimes returns 403 with body null on multiple requests, which is a sync crash in line 101, meanwhile, it should return the error in res.

**Comment by egg-** [comment]
Thank you for your report.
Fedex has created it because it is needed, but since it is not used often, so it only adds basic logic and stops it and I did not prepare for all the errors.
I will do additional development as soon as I can, but I would welcome you if you do PR.
Thank you.

**Comment by chadsparrow** [comment]
I ran into the error on production as well, has it been fixed?
