### ISSUE TITLE
Cannot run in browser (React code)

### ISSUE THREAD

**Issue by TravelingTechGuy** [egg-/delivery-tracker#6]
When attempting to track a FedEx package in my React code, I received:
```
POST https://www.fedex.com/trackingCal/track 403 (Forbidden)
```
And:
```
Access to fetch at 'https://www.fedex.com/trackingCal/track' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Is there any way to set the CORS mode to `no-cors` when running in a browser? Or was the module not meant to be used in a browser? Is the 403 error related, or incidental?

**Comment by egg-** [comment]
Sorry, I did not consider the operation in the browser, and I think it will not be possible because of its behavior.
